#!/bin/bash
# cite-inline
#
# Generate a citation for code used from stackoverflow.
#
# Example
# -------
#
# 1. Generate a citation.
#
# //$ cite -m -u http://stackoverflow.com/questions/3151702/discriminated-union-in-c-sharp
# /*
#    Original code Copyright (c) 2011 cdiggins[1]
#    Modified code Copyright (c) 2016 Shane Celis, @shanecelis[2]
#
#    Licensed under the CC-BY-SA 3.0[3]
#
#    Original code posted to this question[4] and answer[5] from
#    stackoverflow.com where user contributions are licensed under
#    CC-BY-SA 3.0 with attribution required.
#
#    [1]: https://stackoverflow.com/users/184528/cdiggins
#    [2]: https://twitter.com/shanecelis
#    [3]: http://creativecommons.org/licenses/by-sa/3.0/
#    [4]: http://stackoverflow.com/questions/3151702/discriminated-union-in-c-sharp
#    [5]: http://stackoverflow.com/a/7302957/6454690
#  */
#
# 2. Add citations to a file.
#
# If the file LinqExtensions has lines that look like this:
#
#     // http://stackoverflow.com/questions/3151702/discriminated-union-in-c-sharp
#
# A citation will be inserted after that line by running the following command:
#
# $ cite-stackoverflow add-citations LinqExtensions.cs
# warning: Answer not specified for 5 questions; assuming first answer was used.
# warning: Used cache for 15 stackexchange API requests.
#
# 3. Remove citations from a file.
#
# Dependencies: bash, curl, jq, and perl

usage() {
    echo "usage: cite-inline [-hnv] " >&2;
    echo "                    -p -- [cite options] -- " >&2;
    echo "                          add <files>" >&2;
    echo "                          remove <files>" >&2;
    echo "                          clear-cache" >&2;
    echo " -h      Show usage." >&2;
    echo " -n      Do a dry-run: Print to stdout. No file changes." >&2;
    echo " -v      Be verbose." >&2;
    echo " -p      Pass cite options." >&2;
}
if [ -z "$ROOT_PID" ]; then
    export ROOT_PID=$$;
    trap "if ! cite -W $ROOT_PID; then exit $?; fi" EXIT
fi
# trap 'rc=$?; echo "ERR at line ${LINENO} (rc: $rc)"; exit $rc' ERR
# trap 'rc=$?; echo "EXIT (rc: $rc)"; exit $rc' EXIT
set -ueE -o pipefail;
trap '[ $? -ne 0 ] && echo "error: internal script error at line ${LINENO}."' ERR
dryrun=0;
verbose=0;
pass_cite_options=0;
# By default let's use the cache.
while getopts "hnvp" arg; do
    case "$arg" in
        h) usage;
           exit 0;;
        v) verbose=1;;
        n) dryrun=1;;
        p) pass_cite_options=1;;
        *) usage;
           exit 2;;
    esac
done
# Let's pass these on if we call ourselves.
declare -a flags=();
if [ $OPTIND -gt 1 ]; then
    #flags=("${@:0:$((OPTIND))}");
    #echo "flags printf " $(printf "'%s' " "${flags[@]}") >&2;
    :
fi
# echo "flags $OPTIND = '${flags[*]}'" >&2;
#echo "@ printf " $(printf "'%s' " "${@}") >&2;
shift $((OPTIND-1))
#echo "@ after " $(printf "'%s' " "${@}") >&2;


if [ $pass_cite_options -eq 1 ]; then
    while [ "$1" != "--" ]; do
        flags+=( "$1" );
        shift;
    done
    shift;
fi
#echo "@ after2 " $(printf "'%s' " "${@}") >&2;

#exit 0;
if [ $# -lt 2 ]; then
    usage;
    exit 2;
fi

subcommand="$1";
shift;
case "$subcommand" in
    "add")
        perl_flags="-i";
        if [ $dryrun -eq 1 ]; then
            perl_flags="";
        fi
        perl $perl_flags -p -e '
BEGIN{
  undef $/;
  @flags=();
  while ((my $arg = shift) ne "--") {
    push @flags, $arg;
  }
#  print STDERR "flags = ", join(",",@flags), "\n";
  $quoted_flags = join(" ",map(qq("$_"),@flags));
}
s[^\n?((\s*)//\$ cite ([^\\\n]*)(\\\s*//(.*)$)?)$(\s*/\*\s*Original code Copyright[^\*]+\*/\s*$)?\n?]{
  #my $cmd = "cite $quoted_flags -p \"$2\" -u \"$3\"\n";
  my $cmd = "cite $quoted_flags -p \"$2\" $3 $5";
  print STDERR "$cmd\n";
  my $citation = `$cmd`;
  die if $? != 0;
if ($citation !~ /^\s*$/) {
  "$1\n$citation";
} else {
  "\n";
}
}mge' \
        -- ${flags[@]+"${flags[@]}"} -- "$@"; # args
             # https://stackoverflow.com/a/7577209/6454690
        ;;
    "remove")
        flags="-i";
        if [ $dryrun -eq 1 ]; then
            flags="";
        fi
        perl $flags -pe '
BEGIN{undef $/;}
s!^(\s*//$ cite .*)\s*/\*\s*Original code Copyright[^\*]+\*/!$1!smg' \
        "$@";
        ;;
#     "grep-references")
#         perl -ne '
# print if m!^(\s*//\s*http://stackoverflow.com\S+)!;' "$@";
#         ;;
    "clear-cache")
        if [ -d /tmp/cite-stackoverflow/ ]; then
            rm /tmp/cite-stackoverflow/*;
            echo "Cleared cache.";
        fi
        ;;
    *)
        echo "error: no such subcommand '$subcommand'." >&2;
        exit 4;
esac
